# Generated by Django 5.2.5 on 2025-08-27 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_ride_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
