# Generated by Django 5.2.5 on 2025-09-07 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_ride_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='taxi.taxi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('taxi', 'user')},
            },
        ),
    ]
