# Generated by Django 5.2.5 on 2025-09-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_taxirating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_rides', to='taxi.taxi'),
        ),
    ]
