# Generated by Django 5.2.5 on 2025-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
